name: ci

on:
  pull_requests:
    branches: [main]

jobs:
  tests:
    name: Tests
    runs-on: unbuntu-latest

    steps:
      - name: Checks out code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Force Failure
        run: (exit 1)
